config/routes.rb
Photr::Application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'post', to: 'pictures_new#new', as: 'post'

  resources :users
  resources :sessions
  resources :pictures

root :to => 'users#index'
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  has_attached_file :avatar
  validates :caption, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base

has_secure_password

validates :email, uniqueness: true

validates :name, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end
end

app/controllers/pictures_controller.rb
class PictureController < ApplicationController
  def create
    @picture = Picture.create(picture_params)
  end

private
  def picture_params
    params.require(:picture).permit(:avatar)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user), notice: "Thank you for signing up!"
    else
      render "new"
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "User has been updated!"
      redirect_to user_path
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = "User information destroyed."
  end

private
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :username, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photr</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <div id="user_header">
    <% if current_user %>
      Logged in as <%= current_user.email %>.
    <% else %>
    <%= link_to "Sign Up", new_user_path %> or
    <%= link_to "Log In", new_session_path %>
    <% end %>
<%= yield %>
  </div>
</div>
</body>
</html>

app/views/users/index.html.erb
<div class="jumbotron">
  <h1>Welcome to Photr</h1>
  <h4>- the world's premiere photo sharing app-</h4>

  <br>
  <%= link_to "Sign Up for Photr", new_user_path, :class=> "btn btn-primary" %>
</div>



<h3>Here are some Photr-izers you can join:</h3>
<ul class ="bg-primary">
  <% @users.each do |user| %>
    <li> <%= user.name %> </li>
  <% end %>
</ul>

<h6>Copyright '87</h6>

app/views/users/new.html.erb
<h1>Sign Up for Photr</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
    <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions"><%= f.submit "Photr-ize yourself" %></div>
<% end %>

app/views/users/show.html.erb
<h1> Here are all our Photr-izers</h1>

<h4><%= @user.name %> has been created!</h4>